apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml

namespace: nginx-demo

commonLabels:
  managed-by: kustomize
  project: nginx-demo
  deployment-type: standard-app