apiVersion: v1
kind: Service
metadata:
  name: hello-world-api-service
  namespace: hello-world-api
  labels:
    app: hello-world-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: hello-world-api